# Generated by Django 4.1.3 on 2022-11-03 04:47

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deadline',
        ),
        migrations.AddField(
            model_name='project',
            name='deadline_date',
            field=models.DateTimeField(blank=True, null=True, validators=[todo.models.current_date_validator]),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
