# Generated by Django 4.1.3 on 2022-11-04 06:30

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_project_deadline_project_deadline_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, validators=[todo.models.current_date_validator]),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, validators=[todo.models.current_date_validator]),
        ),
    ]
