# Generated by Django 4.1.2 on 2022-10-12 02:26

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_project_description_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, validators=[todo.models.current_date_time_validator]),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, validators=[todo.models.current_date_time_validator]),
        ),
    ]
