# Generated by Django 4.1.2 on 2022-10-14 02:11

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_remove_task_deadline_remove_task_next_occurrence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateTimeField(blank=True, null=True, validators=[todo.models.current_date_validator]),
        ),
    ]
